In [1]:
import numpy as np

In [2]:
a = np.arange(9)
print(a[2:3])

[2]


In [5]:
b = np.arange(24).reshape(2, 3, 4)
print(b)
print('-' * 50)
print(b[1][2][3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------------------------------------
23


In [6]:
# 这才是规范的用法
print(b[1, 2, 1])
print('-' * 50)
print(b[0, :, :])
print('-' * 50)
print(b[1, :, -1])

21
--------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------
[15 19 23]


In [7]:
c = np.arange(12)

In [8]:
c.resize([3, 4])

In [9]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
c.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
c.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [13]:
# 交换0，1轴，在两维时同T
np.rollaxis(c, 0, 1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [14]:
np.append([[1, 2, 3]], [[4, 5, 6]])

array([1, 2, 3, 4, 5, 6])

In [15]:
np.append([[1, 2, 3]], [[4, 5, 6]], axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
np.append([[1, 2, 3]], [[4, 5, 6]], axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [17]:
d = np.arange(6).reshape(2, 3)
d

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
e = np.arange(6, 12).reshape(2, 3)
e

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [19]:
np.hstack((d, e))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [20]:
np.vstack((d, e))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
np.dstack((d, e))

array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])

In [22]:
f = np.arange(60).reshape(3, 4, 5)
f

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [23]:
g = np.arange(60).reshape(3, 4, 5)
g

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [24]:
np.stack((f, g), axis=0).shape

(2, 3, 4, 5)

In [25]:
np.stack((f, g), axis=0)

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]],


       [[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]]])

In [26]:
np.stack((f, g), axis=1).shape

(3, 2, 4, 5)

In [27]:
np.stack((f, g), axis=2).shape

(3, 4, 2, 5)

In [28]:
np.stack((f, g), axis=3).shape

(3, 4, 5, 2)

In [29]:
h = np.arange(12).reshape(3, 4)
h

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
np.vsplit(h, 3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [31]:
np.hsplit(h, 2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [33]:
dt = np.dtype([('name', 'S10'), ('age', int)])
i = np.array([("zhang", 21), ("wang", 25), ("li", 17), ("zhao", 27)], dtype=dt)

In [34]:
np.sort(i, order='name')

array([(b'li', 17), (b'wang', 25), (b'zhang', 21), (b'zhao', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [35]:
np.sort(i, order='age')

array([(b'li', 17), (b'zhang', 21), (b'wang', 25), (b'zhao', 27)],
      dtype=[('name', 'S10'), ('age', '<i4')])

In [36]:
j = np.arange(10)
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.where(j < 5)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [38]:
np.where(j > 5, j, j**2)

array([ 0,  1,  4,  9, 16, 25,  6,  7,  8,  9])

In [39]:
k = np.random.random((3, 4))
k

array([[0.37159357, 0.84864018, 0.82526177, 0.6296317 ],
       [0.06934836, 0.01146338, 0.02132793, 0.40874892],
       [0.04980965, 0.97224982, 0.33413395, 0.89732266]])

In [40]:
k[np.where(k > 0.5)]

array([0.84864018, 0.82526177, 0.6296317 , 0.97224982, 0.89732266])

In [41]:
k[(k > 0.3) & (k < 0.7)]

array([0.37159357, 0.6296317 , 0.40874892, 0.33413395])

In [42]:
k[np.array([2, 1])]

array([[0.04980965, 0.97224982, 0.33413395, 0.89732266],
       [0.06934836, 0.01146338, 0.02132793, 0.40874892]])

In [43]:
k.ravel()

array([0.37159357, 0.84864018, 0.82526177, 0.6296317 , 0.06934836,
       0.01146338, 0.02132793, 0.40874892, 0.04980965, 0.97224982,
       0.33413395, 0.89732266])