In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
a * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [4]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [5]:
1 / a

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [6]:
a**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [7]:
a**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [8]:
a - a

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
a * a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
np.multiply(a, a)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
arr_rnd = np.random.normal(5, 10, (3, 4))
arr_rnd

array([[ 1.12722182e+01,  1.87803522e-02, -1.22147480e+01,
         2.22008847e+01],
       [ 8.58805477e+00,  5.72554029e+00,  8.96488170e+00,
         4.92732767e-01],
       [ 3.16995832e+00, -8.18864576e+00, -2.19856442e+01,
         1.06641817e+01]])

In [13]:
np.rint(arr_rnd)

array([[ 11.,   0., -12.,  22.],
       [  9.,   6.,   9.,   0.],
       [  3.,  -8., -22.,  11.]])

In [14]:
x = np.random.normal(5, 10, (3, 1))
y = np.random.normal(5, 10, (3, 1))

In [15]:
x

array([[ 11.97271196],
       [ 18.59366474],
       [-26.36920652]])

In [16]:
y

array([[24.72433997],
       [ 3.13981762],
       [-9.08194899]])

In [17]:
np.maximum(x, y)

array([[24.72433997],
       [18.59366474],
       [-9.08194899]])

In [18]:
np.minimum(x, y)

array([[ 11.97271196],
       [  3.13981762],
       [-26.36920652]])

In [19]:
np.greater(x, y)

array([[False],
       [ True],
       [False]])

In [20]:
np.less_equal(x, y)

array([[ True],
       [False],
       [ True]])

In [22]:
# 矩阵的乘法，输入的2个数组的维度需要满足矩阵乘法的要求，否则会报错；
# arr.T表示对arr数组进行转置
# np.dot表示对输入的两个数组进行矩阵乘法运算
np.dot(a, a.T)

array([[14, 32],
       [32, 77]])

In [23]:
# 利用inv函数，求解矩阵的逆矩阵（注意：矩阵可变，首先必须是方阵）
from numpy.linalg import inv, solve

arr_lg = np.array([[0, 1, 2], [1, 0, 3], [4, -3, 8]])
arr_inv = inv(arr_lg)
arr_inv

array([[-4.5,  7. , -1.5],
       [-2. ,  4. , -1. ],
       [ 1.5, -2. ,  0.5]])

In [24]:
np.dot(arr_lg, arr_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# numpy.linalg中的函数solve可以求解形如 Ax = b 的线性方程组，其中 A 为矩阵，b 为一维数组，x 是未知变量
A = np.array([[1, -2, 1], [0, 2, -8], [-4, 5, 9]])
b = np.array([0, 8, -9])
X = solve(A, b)
X

array([29., 16.,  3.])

In [27]:
s = np.dot(A, X)
s

array([ 0.,  8., -9.])

In [28]:
np.equal(s, b)

array([ True,  True,  True])

In [29]:
np.max(arr_rnd)

22.20088465662524

In [30]:
np.max(arr_rnd, axis=0)

array([11.27221818,  5.72554029,  8.9648817 , 22.20088466])

In [31]:
np.min(arr_rnd, axis=1)

array([-12.21474801,   0.49273277, -21.98564418])

In [32]:
# 利用自带的随机数生成函数生成5位选手的评委打分结果，一共有7位评委。打分结果用5×7大小的数组表示
votes = np.random.randint(1, 10, (5, 10))
votes

array([[8, 5, 4, 4, 4, 6, 6, 8, 5, 3],
       [2, 9, 5, 3, 3, 8, 5, 9, 4, 1],
       [8, 1, 1, 2, 5, 3, 9, 3, 4, 3],
       [5, 8, 4, 1, 8, 5, 2, 1, 4, 9],
       [5, 2, 7, 6, 9, 5, 3, 4, 2, 4]])

In [33]:
# 总分-最高分-最低分，再求平均，即可求得最终结果
(np.sum(votes, axis=1) - np.max(votes, axis=1) - np.min(votes, axis=1)) / 8

array([5.25 , 4.875, 3.625, 4.625, 4.5  ])

In [34]:
# where 函数中输入3个参数，分别是判断条件、为真时的值，为假时的值
# 在Numpy中，空值是一种新的数据格式，我们用np.nan产生空值
np.where(arr_rnd < 5, np.nan, arr_rnd)

array([[11.27221818,         nan,         nan, 22.20088466],
       [ 8.58805477,  5.72554029,  8.9648817 ,         nan],
       [        nan,         nan,         nan, 10.66418175]])

In [35]:
# 定义函数，购买x件订单，返回订单金额
def order(x):
    if x >= 100:
        return 20 * 0.6 * x
    if x >= 50:
        return 20 * 0.8 * x
    if x >= 10:
        return 20 * 0.9 * x
    return 20 * x


# frompyfunc函数有三个输入参数，分别是待转化的函数、函数的输入参数的个数、函数的返回值的个数
income = np.frompyfunc(order, 1, 1)
# order_lst 为5位顾客的下单量
order_lst = [600, 300, 5, 2, 85]
# 计算当天的营业额
np.sum(income(order_lst))

12300.0