In [1]:
import numpy as np

In [2]:
data0 = [2, 4, 6.5, 8]
arr0 = np.array(data0)
arr0

array([2. , 4. , 6.5, 8. ])

In [3]:
# 创建多维数组
data1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr1 = np.array(data1)
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# 利用dtype关键字，传入合适的数据类型，显式地定义
arr2 = np.array(data1, dtype=np.float32)
arr2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]], dtype=float32)

In [5]:
# 查看arr2的各维度的大小，其结果用tuple表示。tuple的长度，表示数组的维数；具体值表示数组的大小
arr2.shape

(2, 4)

In [6]:
# 通过整形1和0，定义布尔类型的数组
data3 = [[1, 0], [0, 1]]
arr3 = np.array(data3, dtype=np.bool)
arr3

array([[ True, False],
       [False,  True]])

In [7]:
# 更改ndarray的数据类型
data6 = [[1.230, 2.670], [1.450, 6.000]]
arr6 = np.array(data6, dtype=np.float32)
arr6.astype(np.float16)
arr6

array([[1.23, 2.67],
       [1.45, 6.  ]], dtype=float32)

In [12]:
arr6.astype(np.int8)
arr6

array([[1.23, 2.67],
       [1.45, 6.  ]], dtype=float32)

In [13]:
# 对浮点数数组，保留3位有效数字，并禁用科学计数法；小数位数不够，后面不会补0
arr7 = np.array([[3.141592653], [9.8]], dtype=np.float16)  # 定义一个2维数组
np.set_printoptions(precision=3, suppress=True)
arr7

array([[3.14],
       [9.8 ]], dtype=float16)

In [14]:
# 创建一个大小为10的全0数组
np.zeros(10, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [15]:
# 创建一个大小为2×3的全0数组
np.zeros((2, 3), dtype=np.float16)

array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float16)

In [16]:
# 创建一个大小为2×3的全1数组
np.ones((2, 5), dtype=np.int16)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [17]:
# empty 函数返回值为未经过初始化的垃圾值
np.empty((3, 3), dtype=np.int8)

array([[-112,  -27,  -60],
       [-109,  -10,    1],
       [   0,    0,  -32]], dtype=int8)

In [18]:
# 创建一个大小为3×3的单位矩阵
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# 创建3×4的矩形矩阵,eye函数，identity的升级版本
np.eye(N=3, M=4, dtype=np.int8)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int8)

In [20]:
# 创建4×5的矩形矩阵，并且为1的对角线向右偏移1个单位。
np.eye(N=4, M=5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [21]:
# 指定 start、stop、以及step。arange和range一样，是左闭右开的区间。
np.arange(0, 33, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [22]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
np.arange(1, 12, 0.25)

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,
        3.25,  3.5 ,  3.75,  4.  ,  4.25,  4.5 ,  4.75,  5.  ,  5.25,
        5.5 ,  5.75,  6.  ,  6.25,  6.5 ,  6.75,  7.  ,  7.25,  7.5 ,
        7.75,  8.  ,  8.25,  8.5 ,  8.75,  9.  ,  9.25,  9.5 ,  9.75,
       10.  , 10.25, 10.5 , 10.75, 11.  , 11.25, 11.5 , 11.75])

In [24]:
# np.linspace(start, stop[, num=50[, endpoint=True[, retstep=False[, dtype=None]]]]])
arr8 = np.linspace(1, 100, num=30)
arr8

array([  1.   ,   4.414,   7.828,  11.241,  14.655,  18.069,  21.483,
        24.897,  28.31 ,  31.724,  35.138,  38.552,  41.966,  45.379,
        48.793,  52.207,  55.621,  59.034,  62.448,  65.862,  69.276,
        72.69 ,  76.103,  79.517,  82.931,  86.345,  89.759,  93.172,
        96.586, 100.   ])

In [25]:
# 这里定义了一个长度为20的等差数组，然后通过reshape方法，调整数组的大小为6×5
arr8.reshape(6, 5)

array([[  1.   ,   4.414,   7.828,  11.241,  14.655],
       [ 18.069,  21.483,  24.897,  28.31 ,  31.724],
       [ 35.138,  38.552,  41.966,  45.379,  48.793],
       [ 52.207,  55.621,  59.034,  62.448,  65.862],
       [ 69.276,  72.69 ,  76.103,  79.517,  82.931],
       [ 86.345,  89.759,  93.172,  96.586, 100.   ]])

In [30]:
# geomspace()方法，创建指数等比数列
arr9 = np.geomspace(2, 1024, 10, dtype=np.int16)
arr9

array([   2,    4,    7,   16,   32,   64,  127,  256,  512, 1024],
      dtype=int16)

In [31]:
arr9.reshape(5, 2)

array([[   2,    4],
       [   7,   16],
       [  32,   64],
       [ 127,  256],
       [ 512, 1024]], dtype=int16)

In [32]:
# logspace()方法，创建对数等比数列
arr10 = np.logspace(1, 20, num=20, base=2)
arr10

array([      2.,       4.,       8.,      16.,      32.,      64.,
           128.,     256.,     512.,    1024.,    2048.,    4096.,
          8192.,   16384.,   32768.,   65536.,  131072.,  262144.,
        524288., 1048576.])

In [35]:
np.logspace(-6, 6)

array([      0.   ,       0.   ,       0.   ,       0.   ,       0.   ,
             0.   ,       0.   ,       0.   ,       0.   ,       0.   ,
             0.   ,       0.   ,       0.001,       0.002,       0.003,
             0.005,       0.008,       0.015,       0.026,       0.045,
             0.079,       0.139,       0.244,       0.429,       0.754,
             1.326,       2.33 ,       4.095,       7.197,      12.649,
            22.23 ,      39.069,      68.665,     120.679,     212.095,
           372.759,     655.129,    1151.395,    2023.59 ,    3556.48 ,
          6250.552,   10985.411,   19306.977,   33932.218,   59636.233,
        104811.313,  184206.997,  323745.754,  568986.603, 1000000.   ])

In [36]:
arr10.reshape(5, 4)

array([[      2.,       4.,       8.,      16.],
       [     32.,      64.,     128.,     256.],
       [    512.,    1024.,    2048.,    4096.],
       [   8192.,   16384.,   32768.,   65536.],
       [ 131072.,  262144.,  524288., 1048576.]])

In [37]:
# 产生一个大小为3×2，符合0-1之间的均匀分布的数组,创建[0, 1)之间的均匀分布的随机数组
np.random.rand(10)

array([0.79 , 0.073, 0.395, 0.137, 0.427, 0.096, 0.589, 0.102, 0.13 ,
       0.556])

In [38]:
# uniform方法可以指定产生随机数的范围[low, high)，size为数组的形状，输入格式为整形（一维）或者整形元祖
# 如果不指定size的话，则返回一个服从该分布的随机数
np.random.uniform(1, 100, size=(3, 3, 3))

array([[[69.085, 59.324, 12.387],
        [16.859, 16.082, 75.014],
        [70.511, 54.596, 88.381]],

       [[19.73 , 84.021, 88.418],
        [67.092, 94.55 , 26.583],
        [98.5  , 75.223, 75.716]],

       [[32.355, 43.93 , 51.189],
        [25.687, 61.934, 26.993],
        [44.482,  8.462, 53.701]]])

In [44]:
# 该方法和rand类似，函数的输入为若干个整数，表示输出随机数的大小为d0×d1× ...×dn
# 如果没有参数输入，则返回一个服从标准正态分布的float型随机数
np.random.randn(2, 3)

array([[-0.864,  0.742, -0.782],
       [-0.038,  0.322,  0.176]])

In [45]:
# loc:指定均值 μ; scale:指定标准差 σ
# size:输入格式为整形（一维）或者整形元祖，指定了数组的形状
np.random.normal(100, 10, 10)

array([ 80.539,  88.175,  80.864, 105.838,  89.801, 107.585, 114.267,
        91.181, 101.835, 115.08 ])

In [46]:
np.random.normal()

-0.41627724897743096

In [47]:
# 函数返回区间[low, high)内的离散均匀抽样，dtype指定返回抽样数组的数据类型,默认为整形
# size:输入格式为整形（一维）或者整形元祖，指定了数组的形状
np.random.randint(1, 9, (9, 9))

array([[5, 1, 3, 6, 8, 6, 3, 1, 6],
       [8, 2, 1, 7, 6, 5, 7, 1, 1],
       [1, 1, 3, 7, 1, 7, 2, 4, 2],
       [4, 2, 2, 5, 4, 1, 4, 8, 6],
       [5, 6, 6, 3, 2, 1, 2, 4, 2],
       [2, 6, 2, 6, 3, 8, 7, 4, 5],
       [7, 5, 3, 6, 4, 8, 7, 8, 1],
       [7, 5, 1, 4, 2, 3, 2, 5, 2],
       [6, 8, 5, 5, 3, 5, 7, 1, 1]])

In [49]:
# 从样本a中进行抽样，a可以为数组、列表或者整数，若为整数，表示[0,a)的离散抽样；
# replace为False，表示无放回抽样；replace为True，表示有放回抽样，可重复
# size为生成样本的大小
# p为给定数组中元素出现的概率
# numpy.random.choice(a, size=None, replace=True, p=None)
# 因为理想情况下，每次投篮都不影响下一次的结果，所以把这个问题归结为有放回的抽样，一共进行10次
# shoot_lst用来存储投篮的结果
shoot_lst = []
for i in range(10):
    shoot = np.random.choice(['命中', '未命中'], size=1, replace=True, p=[0.8, 0.2])
    shoot_lst.append(shoot[0])
shoot_lst

['命中', '未命中', '命中', '命中', '命中', '未命中', '命中', '命中', '命中', '未命中']

In [50]:
# 花式索引
# 新建4×6的二维数组arr_
arr_demo01 = np.arange(24).reshape(4, 6)
arr_demo01

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [51]:
# 方法1：分别将4个角的元素索引出来，然后把取出来的4个元素，重新组成一个新2×2的数组
arr_method1 = np.array([[arr_demo01[0, 0], arr_demo01[0, -1]],
                        [arr_demo01[-1, 0], arr_demo01[-1, -1]]])
arr_method1

array([[ 0,  5],
       [18, 23]])

In [52]:
# 方法2：利用布尔索引，可以同时索引不连续的行。分别对axis 0方向和axis 1方向进行索引。但是需要注意的是，得分2次索引；
arr_method2 = arr_demo01[[True, False, False,
                          True]][:, [True, False, False, False, False, True]]
arr_method2

array([[ 0,  5],
       [18, 23]])

In [53]:
# 方法3：分别传入4个角的坐标，请朋友们注意观察传入的2个整数数组的规律
arr_demo01[[0, 0, -1, -1], [0, -1, 0, -1]].reshape(2, 2)

array([[ 0,  5],
       [18, 23]])

In [54]:
# 方法4：利用花式索引和切片混用，整体思路和方法2很相似。也是通过连续2次索引，得到一个矩形状的区域
arr_demo01[[0, -1]][:, [0, -1]]

array([[ 0,  5],
       [18, 23]])

In [55]:
# 方法5：利用函数np.ix_，构建矩形索引器：
arr_demo01[np.ix_([0, -1], [0, -1])]

array([[ 0,  5],
       [18, 23]])